apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fintech-db
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: fintech-db
  template:
    metadata:
      labels:
        app: fintech-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: db-credentials
        - configMapRef:
            name: fintech-config
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP # Solo accesible desde dentro del clúster
  selector:
    app: fintech-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432